# Generated by Django 4.2.1 on 2023-10-07 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
