# Generated by Django 4.2.1 on 2023-08-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bids_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='listings',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='auctions.categories'),
        ),
    ]
