# Generated by Django 4.2.1 on 2023-08-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_categories_listings_auction_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenst',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auction_listings'),
        ),
    ]
